### ISSUE TITLE
When the beacon falls, it didnt change it to a chest or a ender chest

### ISSUE THREAD

**Issue by GreyhanNS** [badbones69/Crazy-Envoy#15]
Whenever i type /start envoy, and the beacon is falling when it hits the ground it doesnt change to an envoy. How do i fix this? Please reply as possible.
My Server : mc,monsterscraft.com

**Comment by kicjow** [comment]
You may need to turn off falling blocks. I have seen it happen on other servers but it doesn't happen when i try.
https://github.com/kicjow/Crazy-Envoy/blob/master/Config.yml#L4
