### ISSUE TITLE
[API Request] Adding an event when a player collects an envoy

### ISSUE THREAD

**Issue by rcj0003** [badbones69/Crazy-Envoy#32]
Please add an event to the API that is fired when a player collects an envoy.

Regards

**Comment by badbones69** [comment]
Kinda late reply but if anyone later needs this: https://github.com/badbones69/Crazy-Envoy/blob/master/plugin/src/main/java/me/badbones69/crazyenvoy/api/events/OpenEnvoyEvent.java
