### ISSUE TITLE
Random Location

### ISSUE THREAD

**Issue by jebenii** [badbones69/Crazy-Envoy#6]
Random-Locations: true
  Max-Radius: 500
  Min-Radius: 300

everytime envoys start, using these options the entire server crashes

**Comment by kicjow** [comment]
Strange,  is there land 300-500 blocks away from the center?

**Comment by SilverHuskey** [comment]
My Guess is that you are trying to spawn a lot of crates and your server does not have enough RAM to support this. if this is the case, try reducing the amount of crates dropping and turn the fireworks off.

**Comment by Spazzinq** [comment]
Why do you not close these dusty issues?
