### ISSUE TITLE
Envoy Stopping Randomly 

### ISSUE THREAD

**Issue by Mihiled** [badbones69/Crazy-Envoy#7]
The envoy will countdown and will not start this happens randomly

**Comment by SilverHuskey** [comment]
I had this issue as well... its probably an error in the config. try doing /envoy reload. if the chat then says something like: "there was an internal error while performing this command" you have messed up the config.

**Comment by davidebic** [comment]
Me 2

**Comment by kicjow** [comment]
@Mihiled Please pastebin ur config for me.
@davidebic you also.

**Comment by Spazzinq** [comment]
Why do you not close these dusty issues?
